name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: zpool-mqtt-ha
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: |
            ghcr.io/${{ github.repository }}
            docker.io/gszoboszlai/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log into GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          docker pull $TAG
          docker inspect $TAG
